# Generated by Django 3.1.2 on 2020-10-09 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201009_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_inclusao',
            field=models.DateField(verbose_name='Data de Inclusão'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='quantidade_Pagina',
            field=models.IntegerField(verbose_name='Quantidade de Página'),
        ),
    ]
