# Generated by Django 3.1.2 on 2020-10-09 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201009_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.1)], verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='quantidade_Pagina',
            field=models.PositiveIntegerField(verbose_name='Quantidade de Página'),
        ),
    ]
