# Generated by Django 3.1.2 on 2020-10-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201009_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='quantidade_Pagina',
            new_name='quantidade_pagina',
        ),
    ]
